Updating the index.md with arcconf information
libstorage/libstoragemgmt-doc pull request #16
Opened 2017-08-10 05:54 UTC by brraghav

2017-08-10 09:19 UTC, cathay4t requested changes
@brraghav I am afraid you get the markdown syntax wrong.
You should use something like:
```markdown
* [Microsemi Adaptec and Smart RAID][29]

[29]: doc/array_conf/Arcconf_Conf.html
```

Please at least try to run the github-pages locally to make sure your changes is correct.

2017-08-10 10:26 UTC, brraghav commented
@cathay4t Thanks for the syntax help with the markdown. I understood it now. I debugged with the jekyll and have added the changes to the same PR.

2017-08-10 10:29 UTC, brraghav commented
@cathay4t  Microsemi bundles the arcconf with StorMan package. Hence the installation for StorMan is included in the webpage for the arcconf installation. I cross verified this with User guide of arcconf.

2017-08-10 10:45 UTC, brraghav commented
@cathay4t  I am still making some changes. I will ping you after that for review..

2017-08-10 11:57 UTC, brraghav commented
@cathay4t Please review this PR. I debugged this using the jekyll.
Kindly let me know if any changes required.

2017-08-10 13:13 UTC, cathay4t requested changes
Please let me find a server and actually try it in lab.

2017-08-10 13:13 UTC, cathay4t commented on doc/array_conf/Arcconf_Conf.md
> +title: Arcconf SmartArray Configuration Guide
Should be `Microsemi SAS Controllers Configuration Guide`

2017-08-10 13:13 UTC, cathay4t commented on doc/array_conf/Arcconf_Conf.md
> +website.
The `arcconf` tool is also included in `Microsemi maxView Storage Manager` tool.

2017-08-10 13:13 UTC, cathay4t commented on doc/array_conf/Arcconf_Conf.md
> +* `RHEL 7.1 x86_64`
Please try it on RHEL 7.4 or at least RHEL 7.3.

2017-08-14 14:19 UTC, cathay4t approved these changes
Besides trivial lints, I approve this PR.

2017-08-14 14:19 UTC, cathay4t commented on doc/array_conf/Arcconf_Conf.md
> +* `StorMan-2.05-22885.x86_64.bin`
I failed to find 2.05, but only found `msm_linux_x64_v2_04_22665.tgz` on the website.

And we should suggest user to use rpm instead:

```bash
tar xf msm_linux_x64_v2_04_22665.tgz
sudo yum install ./cmdline/rpm/Arcconf-2.04-22665.x86_64.rpm
```

2017-08-15 13:09 UTC, cathay4t commented
@brraghav Could you update the patch regarding https://github.com/libstorage/libstoragemgmt-doc/pull/16#discussion_r132961859 ?

2017-08-16 12:45 UTC, cathay4t commented
@brraghav Never mind. I will commit another patch to fix the https://github.com/libstorage/libstoragemgmt-doc/pull/16#discussion_r132961859

2017-08-16 12:45 UTC, merged